### PR TITLE
Implement margin for FMC rules fix #315

### LINKED ISSUE #315: Margin for FMC sheet rules
As [suggested](https://github.com/campos20/tnoodle/commit/47e46f56b68a2839c17e7aa592642c3e595306a2#commitcomment-26779950) by @lgarron, we could have nice margins for rules.

Lucas' screenshot

### PR DESCRIPTION
**Pull request by campos20**

### CODE REVIEW

**Comment by campos20** [comment]
Current margin
captura de tela de 2018-01-13 17-31-42

It may not look always (pixel) centered. That's because not every language uses all available space.
captura de tela de 2018-01-13 17-29-48

**Comment by campos20** [comment]
@lgarron, what do you think?

**Comment by campos20** [comment]
Now it's really centered, since we are justifying things.

captura de tela de 2018-01-14 01-46-11

With highlighted rectangles for clarification.

captura de tela de 2018-01-14 01-44-43

captura de tela de 2018-01-14 01-44-28

**Comment by lgarron** [comment]
This looks very nice now! :-)

**Pull request merged**
