### PR TITLE
Replace fitAndShowText fix #306

### LINKED ISSUE #306: Replace fitText function
We have 2 fitText functions, working in different ways. It would be nice to replace the [old one](https://github.com/thewca/tnoodle/blob/master/webscrambles/src/net/gnehzr/tnoodle/server/webscrambles/ScrambleRequest.java#L714) and some [code related](https://github.com/thewca/tnoodle/blob/master/webscrambles/src/net/gnehzr/tnoodle/server/webscrambles/ScrambleRequest.java#L864) with the [new one](https://github.com/campos20/tnoodle/blob/master/webscrambles/src/net/gnehzr/tnoodle/server/webscrambles/ScrambleRequest.java#L774).

### PR DESCRIPTION
**Pull request by campos20**
This is a not messed version of #325
This also fix some issues with rects position, so fitting text will be easier from now.

### CODE REVIEW

**Comment by campos20** [comment]
Everything looks fine, we'll change centering stuffs later.

captura de tela de 2019-01-04 14-27-41

captura de tela de 2019-01-04 14-27-25

**Comment by jfly** [comment]
LGTM. Have you checked that the FMC sheet looks good in every language?

I don't like the idea of merging up a PR that puts TNoodle in an unreleasable state (we wouldn't want to release with this weird centering stuff going on). Do you have a commit ready to fix that? If so, could you add that commit to this PR?

I'm also a bit confused about the commit message. You're talking about `fitText`, but this PR seems to be replacing `fitAndShowText` with `fitAndShowTextNew`, we still have a `fitText`, don't we?

**Comment by campos20** [comment]
> LGTM. Have you checked that the FMC sheet looks good in every language?

Yes, it looks OK :smiley:

 > I don't like the idea of merging up a PR that puts TNoodle in an unreleasable state (we wouldn't want to release with this weird centering stuff going on). Do you have a commit ready to fix that? If so, could you add that commit to this PR?

I was thinking of fix this on #377, but that would also trigger a lot of translation issues (English version would be OK). So, should I just change the layout here as well so it keeps TNoodle releasable? Also, Lucas [mentioned](https://github.com/thewca/tnoodle/pull/377#issuecomment-449892033) some suggestions to layout there, so my plan was to fix that while finishing 377. I'm on vacation so I have a lot of time to work on this.

> I'm also a bit confused about the commit message. You're talking about `fitText`, but this PR seems to be replacing `fitAndShowText` with `fitAndShowTextNew`, we still have a `fitText`, don't we?

Older version of fitAndShowText used some dirty hacks that were messing with translations. When we implemented i18n, we had to create a fitAndShowTextNew, hack free, but we kept fitAndShowText for some cases. Now fitAndShowTextNew does all the work and we renamed it for fitAndShowText. Older version is no longer needed.

**Comment by jfly** [comment]
> So, should I just change the layout here as well so it keeps TNoodle releasable?

Yes please, if that's not too much trouble, I think that's a good way to divide the work and for me to be able to understand what's happening!

> Older version of fitAndShowText used some dirty hacks that were messing with translations. When we implemented i18n, we had to create a fitAndShowTextNew, hack free, but we kept fitAndShowText for some cases. Now fitAndShowTextNew does all the work and we renamed it for fitAndShowText. Older version is no longer needed.

Sorry, I'm still confused. I think I understand what's going on with `fitAndShowTextNew` -> `fitAndShowText`, but I'm talking about [`fitText`](https://github.com/jfly/tnoodle/blob/7ed429c25795f830cd2f8333c9609b758f6acaed/webscrambles/src/net/gnehzr/tnoodle/server/webscrambles/ScrambleRequest.java#L962), which still exists. I'm fine with it still existing, I just think your commit message is referring to `fitText` when it probably should be referring to `fitAndShowText` (or I'm very confused).

**Comment by campos20** [comment]
OK, I'll edit layout here.

> Sorry, I'm still confused. I think I understand what's going on with `fitAndShowTextNew` -> `fitAndShowText`, but I'm talking about [`fitText`](https://github.com/jfly/tnoodle/blob/7ed429c25795f830cd2f8333c9609b758f6acaed/webscrambles/src/net/gnehzr/tnoodle/server/webscrambles/ScrambleRequest.java#L962), which still exists. I'm fine with it still existing, I just think your commit message is referring to `fitText` when it probably should be referring to `fitAndShowText` (or I'm very confused).

You got it right, I wrote it wrongly. For some reason, this fitText wasn't calculating precisely the fontsize. That caused a lot of trouble for i18n. That's why I did not use it during i18n. I'll edit the message.

**Comment by campos20** [comment]
The margin, and align left

captura de tela de 2019-01-05 17-25-22

Regular sheet looks ok as well

captura de tela de 2019-01-05 17-25-11

Verbose language (look at the warning)

captura de tela de 2019-01-05 17-25-54

@lgarron could you please take a look?

**Comment by jfly** [comment]
LGTM!

**Pull request merged**
