### PR TITLE
update min2phase

### PR DESCRIPTION
**Pull request by cs0x7f**
Update min2phase package to the latest version.
The average length of generated scrambles is reduced.
Simple benchmark (default configuration, 200ms):

3x3x3(not restricted)
   old: 19.29
   new: 18.58

333bld(first move restricted)
   old: 19.61
   new: 18.83

333fm(first and last move restricted)
   old: 19.90
   new: 19.18

### CODE REVIEW

**Comment by lgarron** [comment]
> 3x3x3(not restricted)
> old: 19.29
> new: 18.58

Woah, that's quite some impact! :-D

I unfortunately don't have time to review all of this myself.
I presume this is the latest version from https://github.com/cs0x7f/min2phase ?

**Comment by cs0x7f** [comment]
Exactly. Improvements compared with previous version used by tnoodle:
1. Pre move technique is available.
2. 6-axis search is available for move-restricted case (333bld and 333fm)
3. Use more efficient pruning table (especially for phase 2) and search strategy

Owing to these improvements, we are able to find sub-20-move solutions faster or find shorter solutions within specific searching time.

**Comment by campos20** [comment]
@cs0x7f could you please update this? We introduced a feature for using Gradle, some files have been moved.

**Comment by suushiemaniac** [comment]
How do we proceed here?

@cs0x7f It seems like there are still some conflicts. Can you rebase, please?
@jfly How do we proceed with the review? min2phase clearly exceeds my frame of mind... :sweat_smile:

**Comment by jfly** [comment]
> Can you rebase, please

I think @cs0x7f resolved this through merge commits (if you try to "Create a merge commit" to merge this PR up, github will let you, but if you try to "Rebase and merge", it says there are conflicts). @cs0x7f, if you're comfortable rebasing, could you rebase these commits and resolve the conflicts? If not, one of us can take care of it for you.

> How do we proceed with the review

I trust @cs0x7f, although I would like to scan the diff (which I have not done yet). @campos20, are you still planning on doing some scramble distribution analysis?

**Comment by campos20** [comment]
> @campos20, are you still planning on doing some scramble distribution analysis?

Yes, although this should not prevent this PR from being merged. The scramble distribution analysis tool will probably be ready in about 2 weeks.

**Comment by suushiemaniac** [comment]
The file conflicts are all due to the file deletions (files are present on the master branch, so rebase is helpless because the merge commit is omitted during rebasing)

They are unambiguous to resolve, even without understanding the intrinsics of this PR. I would like to proceed with a manual rebase in T-48 @jfly

**Comment by suushiemaniac** [comment]
Manually rebased onto master, closing this thread.

**Pull request closed without merging**
