### PR TITLE
Add gray stuff

### LINKED ISSUE #307: Make the form's lines gray
Hi! I saw in the FMC sheet, the form's lines is 100% black, and that can make the text written there harder to read. So I want to make these lines gray.
I am going to bundle this with **add-wca-id** pull request.
Thanks.

### PR DESCRIPTION
**Pull request by leduyquang753**
This is my implementation on making the form and solution lines gray.

fmc updated

Somehow the borders are also gray, which are weird because they were drawn defore the color change. If you can, please fix this.
Thank you.

(This closes #307)

### CODE REVIEW

**Comment by jfly** [comment]
Hey @leduyquang753. Thanks for sending in this PR! Unfortunately, the diff looks pretty complicated, and I'm not going to have time to look at it before the next TNoodle release. Let's revisit this after @campos20 finishes up #306.

**Comment by leduyquang753** [comment]
That's OK. It means I will have more time to fix my little bugs... :D

**Comment by leduyquang753** [comment]
This code is going to die if #352 is merged. Gotta fix this tomorrow...

**Comment by jfly** [comment]
> WARNING: My future implementation on the new fitAndShowText is going to be even more complicated!

:(

**Comment by jfly** [comment]
@leduyquang753, I'm going to close this. Let's revisit this after #325 gets merged up.

**Pull request closed without merging**
