### PR TITLE
Update Brazilian Portuguese

### PR DESCRIPTION
**Pull request by campos20**
Fit the new layout.

### CODE REVIEW

**Comment by jfly** [comment]
@campos20, could you add a screenshot of how this looks? After that, @pedrosino, could you comment here just confirming that you're okay with the translation?

**Comment by pedrosino** [comment]
Yeah, it's good to me.

**Comment by jfly** [comment]
Ok, still waiting for a screenshot from @campos20.

**Comment by campos20** [comment]
Here we go :)

captura de tela de 2018-01-02 20-16-57

**Pull request merged**
