### PR TITLE
Make scramble sheet ratio aware

### PR DESCRIPTION
**Pull request by campos20**
Everything should look almost like the same.

### CODE REVIEW

**Comment by campos20** [comment]
[Testação groß teste à teste 2020 - All Scrambles.pdf](https://github.com/thewca/tnoodle/files/4111579/Testacao.gross.teste.a.teste.2020.-.All.Scrambles.pdf)

**Comment by campos20** [comment]
Super long names are a problem.

**Comment by suushiemaniac** [comment]
Is the testação PDF from *before* or *after* applying your changes?

**Comment by campos20** [comment]
> Is the testação PDF from _before_ or _after_ applying your changes?

From after

**Comment by suushiemaniac** [comment]
In that case, I'm afraid I have to point out several problems with this PR:
1. The page margins at the left and right side seem **extremely** narrow. Most modern printers can't even print this close to the border of the (physical) page

**Comment by suushiemaniac** [comment]
I took the freedom to merge this as part of my cleanup session :D

**Pull request merged**
