### PR TITLE
Update fr translation

### PR DESCRIPTION
**Pull request by viroulep**
Preview:
fm

@julesDesjardin, @HippolyteM, @zeecho: any chance you could proofread the new version please?
I've proofread it several times but you never know...

### CODE REVIEW

**Comment by zeecho** [comment]
Seems good to me

**Comment by julesDesjardin** [comment]
Looks good to me too !

**Comment by HippolyteM** [comment]
I would have just replaced "tiret" with "emplacement" for clarity sake, but it's not absolutely necessary.
(also "noircissez" may not be the prettiest word. "Rayez" would sounds more natural, even if "noircissez" is the closest translation of "blacken", in this context I find it weird)

But I may be too late.:/

**Comment by viroulep** [comment]
Never too late, see #274

**Pull request merged**
