### PR TITLE
Change 'large' number of multi cubes

### PR DESCRIPTION
**Pull request by jpbulman**
This was posted in a FB discussion

28 is arguably no longer a 'really large' number of cubes to attempt.

### CODE REVIEW

**Comment by campos20** [comment]
MBLD prints 7 scrambles per page so that's why we use 28. We should keep that. If we set this to 63 or 70, this could lead to waste of paper since 28 fits most competitors. Can you please consider this in your PR? Maybe just remove "really large" or update to a number > 28 but not as big as 100, multiple of 7.

**Comment by suushiemaniac** [comment]
Ping @jpbulman

**Comment by jpbulman** [comment]
Ah okay, I didn't notice the multiples of seven, that makes more sense now. I like the idea of replacing the message, maybe something along the lines of "Note: For multiple blindfolded, this is actually the number of scrambles you want generated for each attempt in the round! This should be set to the largest number of cubes a competitor will attempt within a round." ? I'd imagine keeping a default of 28 would probably be fine, that is still somewhat high and probably encompasses most MBLD competitors on average. Thoughts?

**Comment by campos20** [comment]
On top of that, we'll soon replace the layout by a more uniform one (offline and online view). If it's ok for you, I'd like to close this.

**Comment by jpbulman** [comment]
Sounds good!

**Pull request closed without merging**
