### PR TITLE
Actually fixing #399

### PR DESCRIPTION
**Pull request by jfenn3883**
Removed the type specifications in <head> from the javascript resources and type from a <style> tag. Added a utf-8 charset declaration.

### CODE REVIEW

**Comment by jfenn3883** [comment]
I think we got it now @suushiemaniac.

**Comment by suushiemaniac** [comment]
Thanks a lot, @jfenn3883! I will wait for Alexandre to approve this PR, because he submitted the original issue.

**Comment by suushiemaniac** [comment]
Current validation as per the instructions in #399 yields the following results:
2020-01-07-151440_1775x865_scrot
2020-01-07-151450_1758x415_scrot

**Comment by campos20** [comment]
@jfenn3883 please validate the final html version agains the markup validator.

**Comment by suushiemaniac** [comment]
Closing due to inactivity and the deprecation of the old UI interfaces.

**Pull request closed without merging**
