### PR TITLE
Fixing #399

### PR DESCRIPTION
**Pull request by jfenn3883**

### CODE REVIEW

**Comment by suushiemaniac** [comment]
Thank you for taking care of this issue!
Looks fine, I will merge it now because the change does not affect the actual program code.

**Comment by suushiemaniac** [comment]
Come to think of it, this does not fix #399! It fixes #168 instead. It seems you have confused the two issues between your PRs.

**Comment by jfenn3883** [comment]
Thanks for changing it @suushiemaniac!

**Comment by jfly** [comment]
Thanks, @jfenn3883!

**Pull request merged**
